import {
  ArrowRight,
  Baby,
  Bank,
  Bell,
  BookmarkSimple,
  BookOpen,
  Briefcase,
  Camera,
  Car,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  CheckCircle,
  CircleHalf,
  Clock,
  ClockCounterClockwise,
  CreditCard,
  DotsThree,
  FileText,
  Fingerprint,
  Globe,
  GraduationCap,
  Heartbeat,
  House,
  IdentificationCard,
  Info,
  ListChecks,
  Lock,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Microphone,
  PaperPlaneRight,
  Percent,
  Plus,
  QrCode,
  Receipt,
  Scales,
  ShareNetwork,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle,
  Storefront,
  Sun,
  Tray,
  UploadSimple,
  User,
  UsersThree,
  Warning,
  WifiLow,
  X,
} from 'phosphor-react-native';
import { ComponentProps, ComponentType } from 'react';

const registry = {
  home: House,
  bell: Bell,
  search: MagnifyingGlass,
  sparkle: Sparkle,
  chevronRight: CaretRight,
  chevronLeft: CaretLeft,
  chevronUp: CaretUp,
  chevronDown: CaretDown,
  close: X,
  qrCode: QrCode,
  document: FileText,
  creditCard: CreditCard,
  briefcase: Briefcase,
  baby: Baby,
  book: BookOpen,
  car: Car,
  map: MapTrifold,
  mapPin: MapPin,
  bank: Bank,
  graduationCap: GraduationCap,
  family: UsersThree,
  globe: Globe,
  lock: Lock,
  shield: ShieldCheck,
  appearance: CircleHalf,
  accessibility: User,
  tray: Tray,
  info: Info,
  identity: IdentificationCard,
  fingerprint: Fingerprint,
  plus: Plus,
  share: ShareNetwork,
  clock: Clock,
  history: ClockCounterClockwise,
  check: Check,
  checkCircle: CheckCircle,
  scan: Camera,
  arrowRight: ArrowRight,
  scales: Scales,
  percent: Percent,
  warning: Warning,
  receipt: Receipt,
  listChecks: ListChecks,
  uploadSimple: UploadSimple,
  send: PaperPlaneRight,
  microphone: Microphone,
  user: User,
  heartbeat: Heartbeat,
  bookmark: BookmarkSimple,
  filter: SlidersHorizontal,
  sun: Sun,
  storefront: Storefront,
  ellipsis: DotsThree,
  signal: WifiLow,
} as const satisfies Record<string, ComponentType<ComponentProps<typeof Bell>>>;

export type IconName = keyof typeof registry;
export type IconWeight = ComponentProps<typeof Bell>['weight'];

type IconProps = {
  name: IconName;
  size?: number;
  color: string;
  weight?: IconWeight;
};

export function Icon({ name, size = 20, color, weight = 'regular' }: IconProps) {
  const Component = registry[name];
  return <Component size={size} color={color} weight={weight} />;
}
